---
  - name: Get DHCP offer
    script: files/dhcp.py baremetal
    register: dhcp_offer
  - name: Make sure we get an IP offer
    assert:
      that:
        - "dhcp_offer.stdout_lines|length > 0"
      fail_msg: "No IP was offered via DHCP"
  - name: Output the IP offered by DHCP
    debug: msg="{{ dhcp_offer.stdout_lines.0 }}"
